steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - manga-translate
  - --source=.
  - --trigger-http
  - --region=us-east1
  - --allow-unauthenticated
  - --runtime=python37
  - --entry-point=translate_image
  - --memory=256
  - --service-account=mangatranslatoradmin@manga-translator-20200817.iam.gserviceaccount.com